name: tests

on:
    push:
        branches:
            - '**'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            - name: update npm
              run: npm i -g npm@9.6.7 --registry=https://registry.npmjs.org
            - name: run test
              run: |
                  npm ci
                  npx playwright install --with-deps
                  npm run test:all
