name: tests

on:
    push:
        branches:
            - '**'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
            - uses: actions/checkout@v4.1.7
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4.0.3
              with:
                  node-version-file: '.nvmrc'
            # handle NPM / Node.js repeatedly bricking their npm setup on Windows
            - name: Fix npm on Windows
              if: runner.os == 'Windows'
              shell: bash
              run: |
                  npm i npm
            - name: Install Docker on macOS
              if: runner.os == 'macOS'
              shell: bash
              run: |
                  brew install docker
            - name: run test
              shell: bash
              run: |
                  npm ci
                  npx playwright install --with-deps
                  npm run test:all
